add_newline = false
scan_timeout = 30
command_timeout = 300
format = """\
    $username\
    $hostname\
    $directory\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $hg_branch\
    $env_var\
    $docker_context\
    $kubernetes\
    $aws\
    $gcloud\
    $package\
    $dotnet\
    $elixir\
    $elm\
    $erlang\
    $golang\
    $java\
    $julia\
    $nodejs\
    $ocaml\
    $php\
    $purescript\
    $python\
    $ruby\
    $rust\
    $terraform\
    $zig\
    $mise\
    $nix_shell\
    $conda\
    $memory_usage\
    $crystal\
    $cmd_duration\
    $custom\
    $line_break\
    $jobs\
    $battery\
    $time\
    $character\
"""

[character]
success_symbol = "[ ::](#9ece6a)"
error_symbol = "[ ERROR](#f7768e)"
vicmd_symbol = "[ ::](#9ece6a)"

[hostname]
ssh_only = true
disabled = false
style = "#e0af68"

[directory]
truncation_length = 3
truncate_to_repo = false
style = "#7dcfff"
format = "ğŸ‘» [$path]($style)[$read_only]($read_only_style) "

[time]
disabled = false
format = "[$time]($style)"
time_format = "%T"
utc_time_offset = "+9"
style = "#565f89"

[gcloud]
symbol = 'ï¸ğŸ‡¬ï¸ '
#format = 'on [$symbol$account(@$domain)(\($region\))(\($project\))]($style) '
format = 'on [(\($region\))(\($project\))]($style) '
style = 'bold #7aa2f7'
# detect_env_vars = ['GOOGLE_APPLICATION_CREDENTIALS']
[gcloud.region_aliases]
us-central1 = 'uc1'
asia-northeast1 = 'an1'

[aws]
symbol = "â˜ï¸ "
style = "#ff9e64"
[aws.region_aliases]
ap-northeast-1 = "tokyo"
ap-northeast-3 = "osaka"
us-east-1 = "va"
us-east-2 = "oh"
us-west-1 = "ca"
us-west-2 = "or"
#[aws.profile_aliases]
#'sandbox' = 'sandbox'

[docker_context]
symbol = "ğŸ‹ "

[git_branch]
symbol = "ğŸš€ "
#truncation_length = 2
#truncation_symbol = ""
style = "#bb9af7"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[PICKING](bold red)"

[git_status]
ignore_submodules = true
ahead = ""
behind = ""
diverged = "â‡•"
conflicted = "="
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"
renamed = "Â»"
deleted = "âœ˜"

[golang]
#symbol = "ğŸğŸ’¨ "
style = "#7dcfff"

[kubernetes]
symbol = "ğŸ¥‘ "
style = "#e0af68"
disabled = false
format = '[$symbol$context( \($namespace\))]($style) in '
detect_extensions = []
detect_files = ['k8s', 'Dockerfile', 'docker-compose.yml', 'docker-compose.yaml', 'helmfile.yaml', 'helmfile.yml']
detect_folders = ['k8s', 'helm', 'kubernetes', '.kube']
[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "dev"

[nodejs]
symbol = "ğŸ¤– "

[python]
# symbol = "ğŸ‘¾ "
pyenv_version_name = true
pyenv_prefix = "foo "

[ruby]
symbol = "ğŸ”º "

[terraform]
format = "via [$symbol$version]($style) "

[mise]
disabled = false
symbol = 'mise '
style = 'bold #ff9e64'
format = 'on [$symbol$health]($style) '
healthy_symbol = 'âœ”ï¸ '
unhealthy_symbol = 'âŒ '

[battery]
disabled = true

[conda]
disabled = true

[crystal]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[java]
disabled = true

[julia]
disabled = true

[hg_branch]
disabled = true

[nix_shell]
disabled = true

[ocaml]
disabled = true

[php]
disabled = true

[rust]
disabled = true

[singularity]
disabled = true

[zig]
disabled = false

[purescript]
disabled = true
